# Generated by Django 2.0.1 on 2018-02-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20180121_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='attemptCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='feel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
